---
name: Void Containers
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag"
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - full
          - thin
          - thin-bb
          - mini
          - mini-bb
        arch:
          - aarch64
          - aarch64-musl
          - x86_64
          - x86_64-musl
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCHR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: void-robot
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.${{ matrix.flavor }}
          build-args: |
            ARCH=${{ matrix.arch }}
            BOOTSTRAP_VERSION=962218b
          push: true
          tags: |
            ghcr.io/void-linux/void-linux:latest-${{ matrix.flavor }}-${{ matrix.arch }}
            ghcr.io/void-linux/void-linux:${{ github.event.inputs.version }}-${{ matrix.flavor }}-${{ matrix.arch }}
