---
name: masterdirs
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag"
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
          - aarch64-musl
          - x86_64
          - x86_64-musl
          - i686
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCHR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: void-robot
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.masterdir
          build-args: |
            ARCH=${{ matrix.arch }}
            BOOTSTRAP_VERSION=latest
          push: true
          tags: |
            ghcr.io/void-linux/xbps-src-masterdir:latest-${{ matrix.arch }}
            ghcr.io/void-linux/xbps-src-masterdir:${{ github.event.inputs.version }}-${{ matrix.arch }}
